sudo: required
dist: trusty
language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - clang-format-3.5
    - pkg-config
    - libpam0g-dev
    - libcairo2-dev
    - libxcb1-dev
    - libxcb-dpms0-dev
    - libxcb-image0-dev
    - libxcb-util0-dev
    - libev-dev
    - libxcb-xinerama0-dev
    - libxcb-xkb-dev
before_install:
  - "echo 'APT::Default-Release \"trusty\";' | sudo tee /etc/apt/apt.conf.d/default-release"
  - "echo 'deb http://archive.ubuntu.com/ubuntu/ wily main universe' | sudo tee /etc/apt/sources.list.d/wily.list"
  - sudo apt-get update
  - sudo apt-get --force-yes -y install -t wily libxkbcommon-dev libxkbcommon-x11-dev
script:
  - make -j
deploy:
  provider: releases
  api_key:
    secure: maVMhM/zLUBleVEOhYFRGvTSbL3FnlebSjOcMVvOMnl0IkhOFTnh1wzySe03DPOQKZGBNTJisb9uEL4qp7g6sLt8yHPtRrXL1g0sfYIauFlQanAF9WwUCMBmLzn0hGw+DLiy81zSLvXiC2xY9r1G+qDnS8CHuITpPLDXMBjDa+/uCZk37nLhX1SjL6bHbovK63kpLgLvsA8PvBULXMD4oNhbP/ComXVztGHu5SyvDkV6W1jyM83eStFub3Lq3rDCPs9Oilw0sAZaIP21QMEFdjHjhqon8enVICF2q/4k9O2Kgo94ikqlJpMwSgRDQ5uHjkKGzDjVxtaE7CJP8iI+eL2hNI0AE371w8pLQ4xfhqEI8tSvWXa/r2ACTq0KIgo1viMkqc0KPLjWKJz7STDZkIpEMrfutlnKQvpPnb7DzfXb2RFgW2lQZSYVH76egWjxIk3ZAWOzUBOTVZUcYcjQik3j5EieerqGb3cd5c/qkKuD0BhbrBdQnGIAPmh2lPLt/UDGGv+AIhlfDuaOBWExVHMmMTgxhgAqwnzaa0eN8m4TF1LnS+7hH6VGB6KQzSl002CjqbIjUqZLxKL8+kyu7QFc2LCmxsolRjAxajGJUcueSjODsIy27iGGi3xj3osUts+1HmGE4seB0iJIo5Ke/dt+4LXWDddB6DuhIQAbnI4=
  file: epi3lock
  on:
    tags: true
    repo: ItzaPhenix/epi3lock
